version: '2'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./ui:/opt/app
      - /opt/app/node_modules
    user: "1000:1000"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./api:/opt/app
    depends_on:
      - db
      - queue
    user: "1000:1000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - queue
    volumes:
      - ./backend:/opt/app
    user: "1000:1000"
  db:
    image: postgres
  queue:
    image: rabbitmq
    ports:
      - "5672:5672"
