version: '2'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./ui:/opt/app
      - /opt/app/node_modules
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./api:/opt/app
    # depends_on:
    #   - ui
    #   - db
    #   - queue
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - queue
  # db:
  #   image: postgres
  # queue:
  #   image: rabbitmq
